from mathutils import Vector
from .roof_flat import RoofFlat
from item.facade import Facade
from item.roof_flat_multi import RoofFlatMulti as ItemRoofFlatMulti


class RoofMulti:
    
    def do(self, footprint):
        roofItem = self.init(footprint)
        if footprint.valid:
            if footprint.innerPolygons:
                if self.renderAfterExtrude:
                    self.render(footprint, roofItem)
                else:
                    self.extrude(footprint, roofItem)
                    footprint.roofItem = roofItem
                    footprint.roofRenderer = self.roofRenderer
                footprint.bldgPart.footprint = footprint
            else:
                footprint.element.makePolygon()
                self.volumeAction.volumeGenerators[footprint.getStyleBlockAttr("roofShape")].do(
                    footprint
                )
    
    def extrudeInnerPolygons(self, footprint, roofItem):
        #
        # deal with the inner polygons below
        #
        facades = footprint.facades
        verts = footprint.element.l.genVolumes.verts
        indexOffset = len(verts)
        
        for innerPolygon in footprint.innerPolygons:
            numVerts = innerPolygon.numEdges

            self._generateVerts(footprint, innerPolygon, roofItem)

            vectors = innerPolygon.getVectors()
            
            # the starting side
            _in = indexOffset+numVerts
            facades.append(
                Facade(
                    footprint,
                    (_in-1, indexOffset, _in, _in+numVerts-1),
                    next(vectors),
                    self,
                )
            )
            # the rest of the sides
            facades.extend(
                Facade(
                    footprint,
                    (indexOffset+i-1, indexOffset+i, _in+i, _in+i-1),
                    vector,
                    self
                ) for i,vector in zip(range(1, numVerts), vectors)
            )
            # mark the created facades as inner
            for i in range(-numVerts, 0):
                facades[i].outer = False
            
            indexOffset += 2*numVerts
    
    def init(self, footprint):
        data = self.data
        roofItem = super().init(footprint)
        if not footprint.valid:
            return
        
        if footprint.building.innerPolygons:
            footprint.innerPolygons = footprint.building.innerPolygons
        return roofItem


class RoofFlatMulti(RoofMulti, RoofFlat):
    
    def __init__(self, data, volumeAction, itemRenderers):
        super().__init__("RoofFlatMulti", data, volumeAction, itemRenderers)

    def extrude(self, footprint, roofItem):
        super().extrude(footprint, roofItem)
        self.extrudeInnerPolygons(footprint, roofItem)
    
    def getRoofItem(self, footprint):
        return ItemRoofFlatMulti(
            footprint,
            self.getRoofFirstVertIndex(footprint)
        )
    
    def doFootprintOnly(self, footprint):
        """
        This method is used to generate a footprint only, without any volume with a roof.
        The volume with a roof and further details will be generated by a Geometry Node setup.
        """
        self.init(footprint)

        if footprint.valid:
            # the outer polygon
            super().doFootprintOnly(footprint)

            # the inner polygons
            if footprint.innerPolygons:
                facades = footprint.facades
                verts = footprint.building.element.l.genHoles.verts
                indexOffset = len(verts)
                for innerPolygon in footprint.innerPolygons:
                    numVerts = innerPolygon.numEdges
                    verts.extend(Vector((v[0], v[1], 0.)) for v in innerPolygon.verts)

                    vectors = innerPolygon.getVectors()

                    # the starting side
                    facades.append(
                        Facade(
                            footprint,
                            (indexOffset+numVerts-1, indexOffset), # only indices of the lower facade edge
                            next(vectors),
                            self,
                        )
                    )
                    # the rest of the sides
                    facades.extend(
                        Facade(
                            footprint,
                            (indexOffset+i-1, indexOffset+i), # only indices of the lower facade edge
                            vector,
                            self
                        ) for i,vector in zip(range(1, numVerts), vectors)
                    )
                    # mark the created facades as inner
                    for i in range(-numVerts, 0):
                        facades[i].outer = False
                    
                    indexOffset += numVerts

            footprint.bldgPart.footprint = footprint